#!/bin/zsh
echo "Closing All Apps"
    osascript <<'APPLESCRIPT'
set skipList to {"Finder", "Terminal", "iTerm2"}
tell application "System Events" to set guiApps ¬
    to (name of every application process whose background only is false)
repeat with aName in guiApps
    set aName to aName as text
    if skipList does not contain aName then
        try
            tell application aName to quit 
        end try
    end if
end repeat
APPLESCRIPT
if [[ "$1" == "code" ]]; then
    sleep 2
    echo "Opening Github"
    open "https://github.com/isaacjerish"
    echo "Opening Spotify"
    open -a "Spotify"
    echo "Opening VS Code"
    open -a "Visual Studio Code"
fi